spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    mode: HTML5

  datasource:
    url: jdbc:mysql://152.136.145.182:3306/miaosha
    username: yangweiye_admin
    password: 1998yang
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      max-active: 20
#      initial-size: 5
#      max-wait: 60000
#      min-idle: 10
#      pool-prepared-statements: true
#      max-open-prepared-statements: 20

  redis:
    host: yangweiye.cn
    port: 6379
    password: 1998yang
    timeout: 2000

    jedis:
      pool:
        max-idle: 3
        min-idle: 1
        max-active: 5
        max-wait: 2000
  cache:
    cache-names: redisCache
    type: redis
    redis:
      cache-null-values: true
      use-key-prefix: false
      key-prefix: demo_
      time-to-live: 300000
mybatis:
  #这玩意不生效
  mapper-locations: classpath:com/yangweiye/miaosha/mapper/*Mapper.xml
  type-aliases-package: com.yangweiye.miaosha.pojo
  type-handlers-package: com.yangweiye.miaosha.TypeHandler
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 80